theme: jekyll-theme-minimal
title: Ronald Mego
description: Chief Data Analytics Officer | Data & AI Leader
logo: https://avatars.githubusercontent.com/u/17481958
social_links:
  linkedin: ronaldmego
github_username: ronaldmego