title: Ronald Mego - CDAO
description: Chief Data Analytics Officer | Data & AI Leader
logo: https://avatars.githubusercontent.com/u/17481958
favicon: /assets/images/favicon.png
social_links:
  linkedin: ronaldmego
  twitter: MGOData
github_username: ronaldmego

# Collections configuration
collections:
  projects:
    output: true
    permalink: /portfolio/:path/

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Defaults for posts and projects
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"