title: Ronald Mego - CDAO
description: Chief Data Analytics Officer | Data & AI Leader
logo: https://avatars.githubusercontent.com/u/17481958
favicon: /assets/images/favicon.png
social_links:
  linkedin: ronaldmego
  twitter: MGOData
github_username: ronaldmego